[package]
name = "dconv"
version = "0.2.2"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
chrono = "0.4.41"
clap = { version = "4.5.40", features = ["derive"] }

[profile.release]
lto = "fat"
codegen-units = 1
panic = "abort"
